spring.application.name=envios
server.port=8082

spring.datasource.url=jdbc:sqlserver://localhost:14330;databaseName=EnviosDB;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=727321
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.open-in-view=false